.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. cicoin_qt test_cicoin_qt
clean: FORCE
	$(MAKE) -C .. cicoin_qt_clean test_cicoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_cicoin_qt_check
cicoin-qt cicoin-qt.exe: FORCE
	 $(MAKE) -C .. cicoin_qt
